### ISSUE TITLE
有电子版的吗

### ISSUE THREAD

**Issue by skierlin** [apachecn/math#26]
老哥，求电子版～

**Comment by chenyyx** [comment]
@skierlin 大佬，还没电子版呢

**Comment by daorui** [comment]
大神，看着你的笔记学mit线代呢，怎么25课之后就显示不出来了，求更新啊。

**Comment by yumh** [comment]
我想打印一下，老哥能把，各个章节都转成pdf吗？

**Comment by daorui** [comment]
转成pdf：把内容复制到word里，另存为pdf即可。（office 2010及以上版本应该都可以）

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 赫赫 <notifications@github.com>
发送时间: Wednesday, October 31, 2018 12:34:04 PM
收件人: apachecn/math
抄送: daorui; Comment
主题: Re: [apachecn/math] 有电子版的吗 (#26)


我想打印一下，老哥能把，各个章节都转成pdf吗？

―

**Comment by yumh** [comment]
好的，谢谢了！

**Comment by wizardforcel** [comment]
尝试构建失败，有空了再修复吧。。。

**Comment by yumh** [comment]
这个有整理 完整的pdf版本吗？求发一份1085813590@qq.com

**Comment by bitLiuYang** [comment]
我整理了一下，转化为pdf了。
链接：https://pan.baidu.com/s/1MZ1AZ5W5qKMs1ckVjAjEoQ 
提取码：82eg

**Comment by wangcz-0730** [comment]
请问25张后面怎么显示...看到最精彩的部分了....教程太棒了!!!

**Comment by duoluodeyouhei** [comment]
> 我整理了一下，转化为pdf了。
> 链接：[https](https://pan.baidu.com/s/1MZ1AZ5W5qKMs1ckVjAjEoQ)
> ://pan.baidu.com/s/1MZ1AZ5W5qKMs1ckVjAjEoQ提取码：82eg

**Comment by lin3fei** [comment]
非常感谢


| |
lin3fei
|
|
lin3fei@126.com
|
签名由网易邮箱大师定制
在2019年10月26日 18:48，bao zheng<notifications@github.com> 写道：

我整理了一下，转化为pdf了。
链接：https://pan.baidu.com/s/1MZ1AZ5W5qKMs1ckVjAjEoQ提取码：82eg
