### ISSUE TITLE
3.3.1 交换2*2矩阵有误

### ISSUE THREAD

**Issue by lifangzheng** [apachecn/math#27]
[[0 1], [1, 0]] * [[a b], [c d]] 应为 [[c d], [a b]]

**Comment by chenyyx** [comment]
好的，感谢大佬指出，我去修改一下

**Comment by chenyyx** [comment]
大佬，能不能麻烦您提一个 PR？能记录下您的贡献，我也好直接合并，感谢。

**Comment by lifangzheng** [comment]
不是大佬。。恶补线代的小白。。不太懂用github。。
另外图片是你做的吗？15节以后明显是从某页面或者pdf截图的，想知道原文在哪里？

**Comment by chenyyx** [comment]
@lifangzheng 大佬，那个是我自己用的名字叫做 cmd 的 markdown 编辑器编辑了之后截图再上传的图片，嘿嘿，略微有些尴尬，
